### ISSUE TITLE
Create key for sorting

### ISSUE THREAD

**Issue by lorenzwalthert** [krlmlr/styler#112]
`line1`/ `col1` is no longer a unique sorting (composite) key because we insert tokens like with 
`add_brackets_in_pipe()`. One way to go about that would be to setting `col1`/ `col2` of these tokens 
"in between" the existing tokens. New tokens could then get intermediate values (e.g., when `()` is added: key + 1/3 and key + 2/3 respectively).
See discussion in #111 R/visit.R L136+.

**Comment by krlmlr** [comment]
Reference: https://github.com/krlmlr/styler/pull/111#discussion_r131527625

**Comment by lorenzwalthert** [comment]
Reference ([#119](https://github.com/krlmlr/styler/pull/119#discussion_r132647691)).

**Comment by lorenzwalthert** [comment]
Maybe can simply use column `id`. Check with help file of `getParseData()`.

**Comment by lorenzwalthert** [comment]
Reference: #147.
