### ISSUE TITLE
user-control via transformers

### ISSUE THREAD

**Issue by lorenzwalthert** [krlmlr/styler#113]
In general, all modifications on the parse table that are done with transformer functions can be controlled by the user via the transformer argument. Hence, it may be good to double check whether everything the user may wants to do differently than our default implementation and that can be done with a visitor is in fact done with a visitor and the corresponding transformer function is taken from the transformer argument.

**Comment by lorenzwalthert** [comment]
Reference (#111, second review comment of @krlmlr).

**Comment by krlmlr** [comment]
Reference: https://github.com/krlmlr/styler/pull/111#discussion_r131586378. To get this URL, I right-clicked the "one hour ago" link right to your user name for your comment that starts with "Another advantage of using..."

**Comment by lorenzwalthert** [comment]
Ok, I think I finally get it now... 😊

**Comment by lorenzwalthert** [comment]
@krlmlr It seems to me that this trick isn't working properly anymore.

**Comment by krlmlr** [comment]
I just clicked on the `#111 (comment)` link and it took me to the proper target. I could also right-click the "6 days ago" link of the target to get the URL. A browser issue?

**Comment by lorenzwalthert** [comment]
I think with the redesign of the API (#123), this can de closed since #111 is a separate issue.
