### ISSUE TITLE
remove relicts of flat styling completely

### ISSUE THREAD

**Issue by lorenzwalthert** [krlmlr/styler#121]
This includes changing the argument structures of some exported functions.

**Comment by lorenzwalthert** [comment]
Reference ([#120](https://github.com/krlmlr/styler/pull/120#discussion_r132844820)).

**Comment by lorenzwalthert** [comment]
Actually not really closed, since only top-level API was redesigned, underlying functions are still in the source code.

**Comment by lorenzwalthert** [comment]
I was wondering what we should do with the initial vignette **Data structures** that was part of the GSOC application. If we remove all code we don't use with the nested styling, we can't build that vignette anymore. @krlmlr what do you think? The other vignettes only need minor adaptions.

**Comment by krlmlr** [comment]
If the vignette doesn't build, we can still keep the rendered Markdown version (still stored as `.Rmd` with a YAML front-end).

**Comment by lorenzwalthert** [comment]
Ok, but I think the CI builds fail (e.g. [here](https://ci.appveyor.com/project/lorenzwalthert/styler-bp2vm/build/1.0.295) so we probably need to adapt the build specifications somehow. This probably also concerns the CRAN release I guess...

**Comment by lorenzwalthert** [comment]
@krlmlr What do you think? We can also set `knitr::opt_chunk$set(eval = FALSE)` and add a note to the vignette that commit xyz must be checked out for it to work.

**Comment by krlmlr** [comment]
I'd rather just knit once to Markdown and overwrite the relevant parts of the `.Rmd` file (everything below the YAML header) with the contents of the `.md` file.
