### ISSUE TITLE
Get rid of use_raw_indention

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/styler#129]
Requires valid initialization of `indent` column for nested parse data. Seems tricky.

**Comment by lorenzwalthert** [comment]
With #217, I think we can adapt the paradigm that the transformers do not need to be functions, but can also be options. Also, with `create_style_guide()`, we have a safe constructor function to avoid confusion of the user. Plus, I think this approach is more flexible for going forward. Therefore, I propose to abandon the idea.
