### ISSUE TITLE
rename create_filler()

### ISSUE THREAD

**Issue by lorenzwalthert** [krlmlr/styler#132]
I think this function name is a bit confusing and I would change it so somthing that reflects the purpose of the function better, like `initialize_attributes()` or something like that. I think this is important because people developing their own style guides will get in touch with this function, so it is not purely internal. Alternatively, we can also spit it up into multiple functions and give each a specific name like

* initialize_multi_line
* compute_space
* compute_newline
* initialize_ref_id
* initialize_indent

Which may be more clear but calling 5 functions instead of 1 on every level of nesting might add too much overhead. @krlmlr What's your take on that?

**Comment by krlmlr** [comment]
We should keep exposing one function for initializing internal attributes with a clear name like `initialize_attributes()`, which calls the five functions you're suggesting. I wouldn't worry about performance unless we can measure it.

Is this function part of the public API?

**Comment by lorenzwalthert** [comment]
Ok, fine. No, it's not part of the public API but `create_style_guide()`has an argument `filler`, which stems from `create_filler()` and I think it's not usefull either. So we would change both I suggest.
