### ISSUE TITLE
user feedback: handling overwriting 

### ISSUE THREAD

**Issue by lorenzwalthert** [krlmlr/styler#162]
A test user suggested adding a warning to the help files of functions that overwrite files (like `style_file()`) or even introduce an option to write to a new file instead of overwriting. @krlmlr what do you think?

**Comment by krlmlr** [comment]
A warning in the help should be enough. With version control the overwriting issue is less of a problem.

**Comment by lorenzwalthert** [comment]
Yes, I agree.
