### ISSUE TITLE
Remote dependency pkgload

### ISSUE THREAD

**Issue by lorenzwalthert** [krlmlr/styler#169]
https://github.com/krlmlr/styler/blob/dd23ac99601b21480f5ad4a778b2fc2e90a5c5f1/DESCRIPTION#L26

Can we leave this as is for the CRAN submission?
Reference: #145.

**Comment by krlmlr** [comment]
Do we use it at all?

**Comment by lorenzwalthert** [comment]
Not anymore, we used to use it in the vignette on "Manipulating the nested parse table", but since we replaced all code with the YML output because of #121, I think we can drop that dependency.

**Comment by krlmlr** [comment]
Let's drop it then.

**Comment by lorenzwalthert** [comment]
Closed by https://github.com/krlmlr/styler/commit/3ad76a75b7c41571a95765ce03a4e902f6efca01
