### ISSUE TITLE
Introduce class `vertical`

### ISSUE THREAD

**Issue by lorenzwalthert** [krlmlr/styler#173]
To avoid 
```r
style_text(...) %>%
  cat(sep = "\n")
```
And simply write
```r
style_text(...)
```

**Comment by lorenzwalthert** [comment]
There is one obstacle: The tests won't pass anymore since the output of `style_text` is not the same as the reference with regard to the attributes. However, when written to the file, the text is identical. `test_collection()` uses `utf8::transform_lines_enc()`, which test whether the input and the transformed output is identical via `identical()`, which seems a bit too strict for our case. It seems to me that `all.equal(..., check.attributes = FALSE)` would be more accurate in our situation. Should we adapt `test_collection` to not rely on `utf8::transform_lines_enc()` for the comparison?

**Comment by lorenzwalthert** [comment]
@krlmlr can you advise on that?

**Comment by krlmlr** [comment]
Can you insert an `unclass()` somewhere before checking equality or before calling `transform_...()`?
