### ISSUE TITLE
bang operator and spacing

### ISSUE THREAD

**Issue by lorenzwalthert** [krlmlr/styler#176]
https://github.com/krlmlr/styler/blob/ef10c291034c05957c7a9f9d870db604f99f712a/R/rules-spacing.R#L189

I was wondering whether this rule is really doing what you expect because it turns
```r
a <- ! !!x
```
Into 
```r
a <- !!! x
```
Which is not the same anymore.

@krlmlr probably we should only remove spaces if the token after is not `!`? Because we still want
```r
a <- ! FALSE
```
to become 
```r
a <- !FALSE
```

**Comment by krlmlr** [comment]
Agree that we need to check if the token after is also a bang.
