### ISSUE TITLE
Invalid scope argument needs error

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/styler#177]
`styler::style_pkg(scope = "aasdf")` starts to style my package...

**Comment by lorenzwalthert** [comment]
Right... I was wondering about assertive tests in general. I used `checkmate` but I can't really remember why not having choosed `assertr`, `assertive` or `assertthat`. Any preference on your side?

**Comment by krlmlr** [comment]
A simple `match.arg()` would suffice here IMO.

**Comment by lorenzwalthert** [comment]
So just for `scope` or systematically for all arguments in all exported functions?

**Comment by krlmlr** [comment]
We should apply stricter argument checking everywhere, but `scope` seems more urgent because it does the wrong thing if the value has a typo.

**Comment by lorenzwalthert** [comment]
There actually exists a check in `tidyverse_style(scope = "...")` when the ordered factor is created from `scope`. 
``` r
cat(styler::style_text("a", scope = "abc"), sep = "\n")
#> Error in character_to_ordered(scope, c("none", "spaces", "indention", : all values in scope must be one of the following: none, spaces, indention, line_breaks, tokens
```
Note that `style_text()` does use `utf8::transform_lines_enc()`, which itself implements some error handling.

Styling one file also seems to work (at least outside the `styler`Rproj):
```r
> style_file("/Users/lorenz/Documents/short-term back-up/assertive.R", scope = "3")
#> Styling 1 files:
#> assertive.R. [DONE]
#> No files changed.
#> Warning message:
#>" When processing assertive.R: all values in scope must be one of the following: none, spaces, 
#> indention, line_breaks, tokens 
```
But as you said, an error occurs with `style_pkg()` and also `style_dir()`. I don't understand why though... It also gives the "[...] all values in scope must be one of the following: none, spaces, indention, line_breaks, tokens [...]" warning, but it seems as execution is continued, which then produces these warnings: "In reduce_index(.x, .init, left = .left) :"

**Comment by lorenzwalthert** [comment]
Implementing the `scope` check at the point where we create the ordered factor, i.e. in `tidyverse_style()` seems to be the right place to me though.

**Comment by lorenzwalthert** [comment]
@krlmlr any ideas fro your side?

**Comment by krlmlr** [comment]
Maybe construct the style guide object early on, before calling `transform_files...()`?

**Comment by lorenzwalthert** [comment]
Well it is alread constructed before the body of the style_text() and friends is executed.  However, we could use force(transformers) in the closure make_transformers() to solve the problem. Not sure whether there are more elegant ways but this approach seems to works.

**Comment by krlmlr** [comment]
Yes, lazy evaluation bites sometimes. I'd suggest to `force(style)` in each interface function.

**Comment by lorenzwalthert** [comment]
I think in the end we need to force transformers , since style is only used to creat transformers by default and you actually don't need to supply the argument. I thought about that too but isn't that a bit redundant? What's the advantage to call it in every style* function over calling it once?

**Comment by krlmlr** [comment]
A `force()` call in `make_transformer()` seems sufficient too.
