### ISSUE TITLE
Consider removing dplyr and possibly purrr dependencies?

### ISSUE THREAD

**Issue by jimhester** [krlmlr/styler#181]
dplyr is a very heavy dependency which makes using **styler** on CI services such as travis or appveyor problematic.

Doing this would be useful so you could style the package as a CI step and ensure there are no changes as a way to verify that PRs conform to the style. But this will only work well if styler has limited (and light) dependencies.

If you are open to the possibility of removing the dependency I could work on a PR.

**Comment by krlmlr** [comment]
I think removing dplyr and using compat-purrr.R is a good plan. Happy to review a PR.

**Comment by lorenzwalthert** [comment]
I think since I know the project fairly well by now, I can start working on this in about two weeks if @jimhester is ok with that. If I remember correctly, the majority of dplyr calls was already removed with #90, so it should not be too much of work.

**Comment by jimhester** [comment]
I have a WIP at https://github.com/krlmlr/styler/pull/182.

I also realized that tidyr also has a dplyr dependency, so we would need to remove tidyr as well.

**Comment by lorenzwalthert** [comment]
Yes that might be tricky. Especially for creating the nested parse data - as the name says - we heavily rely on tidyr.

**Comment by jimhester** [comment]
tidyr wasn't bad https://github.com/krlmlr/styler/pull/183

**Comment by jimhester** [comment]
dplyr (#182) is complete now as well. Purrr is fairly light these days, we can remove it if we want, but probably not really needed.

**Comment by krlmlr** [comment]
Should be good now.
