### ISSUE TITLE
PRs pass tic but not R CMD Check

### ISSUE THREAD

**Issue by lorenzwalthert** [krlmlr/styler#186]
I note that various PRs (e.g. #183, not merged or #179, merged) that do [not pass](https://travis-ci.org/krlmlr/styler/builds/272236933#L1365) `R CMD Check` on travis, but are showed as passing on the conversation tab of the PR.
@krlmlr Is that an issue with tic? 
I submitted #185 to fix `R CMD Check`. The error was arguably introduced with #174.

**Comment by krlmlr** [comment]
This may be a change in rcmdcheck, tic expects a named list with components `errors`, `warnings` and `notes` as a result of `rcmdcheck::rcmdcheck_()`. @gaborcsardi: Can you please confirm?

**Comment by gaborcsardi** [comment]
Those components are still there, but there are some new ones as well.

**Comment by lorenzwalthert** [comment]
I merged #185, so the master branch R CMD Check is perfect again, but we can rebuild previous PRs such as #179 that suffer from the same problem.

**Comment by gaborcsardi** [comment]
OK. (I don't understand, though, #185 is only adding a single space, seemingly.)

**Comment by lorenzwalthert** [comment]
Yes, I only added a space, but this space is needed for the tests to pass. Most tests in styler are "take a file, style it and compare it to a reference file". So I updated the reference file because before, the styling rule was adapted and yields a different outcome than before.

**Comment by gaborcsardi** [comment]
Oh, so this is not an `rcmdcheck` issue then.

**Comment by lorenzwalthert** [comment]
@krlmlr so should we file an issue in tic and close this?

**Comment by krlmlr** [comment]
@gaborcsardi: I can replicate locally.

```sh
git clone https://github.com/krlmlr/tic.package.git --branch f-test-failure
cd tic.package
R -q -e 'remotes::install_github("ropenscilabs/tic")'
R -q -e 'install.packages("rcmdcheck")'
R -q -e 'tic::script()' # fails to fail
R -q -e 'remotes::install_github("r-lib/rcmdcheck")'
R -q -e 'tic::script()' # fails successfully
```

How do I reliably count the errors, warnings, and notes from an rcmdcheck object in both the CRAN and GitHub versions?

**Comment by gaborcsardi** [comment]
I don't understand. So this is an `rcmdcheck` issue, then? How are you doing it now? This should do it:
```
length(x$errors) + length(x$warnings) + length(x$notes)
```

**Comment by krlmlr** [comment]
Relevant code in tic looks similar: https://github.com/ropenscilabs/tic/blob/master/R/steps-rcmdcheck.R#L13

It seems to work as expected with the GitHub version of rcmdcheck, but not with the CRAN version of rcmdcheck, this is what my reprex above demonstrates.

**Comment by gaborcsardi** [comment]
This seems to be a bug in the CRAN version of `rcmdcheck`. The error is not even found.

**Comment by lorenzwalthert** [comment]
Am I right that the next `rcmdcheck` CRAN release is going fix this so we can close this issue?

**Comment by krlmlr** [comment]
tic will install rcmdcheck from GitHub for now, please watch out for check failures that are not recognized by Travis or AppVeyor.

**Comment by lorenzwalthert** [comment]
WIth #205, I get perfect local `rcmdcheck::rcmdcheck()`, one NOTE with `devtools::test()` because of a top level file in the directoy (which is not checked in git) and an early terminated CI using `tic`.

**Comment by krlmlr** [comment]
NOTEs currently don't cause a test to fail, but this can be changed in `tic.R`. Should we?

**Comment by lorenzwalthert** [comment]
Well since the offending file causing `devtools::check()` (and not `dectools::test()` as stated above) is not checked into git, the note is not the problem on our CI (it's rather that `rcmdcheck::rcmdcheck()` should give me a NOTE locally).  My main point, however, was that as with [#205](https://travis-ci.org/krlmlr/styler/builds/277010350?utm_source=github_status&utm_medium=notification), I don't see a X ERRORS, Y WARNINGS, Z NOTES at the end of the process (which I expect).

**Comment by krlmlr** [comment]
Yeah, tic should print a summary.
