### ISSUE TITLE
Wrong indention of else if braces are missing

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/styler#191]
``` r
styler::style_text("{if (TRUE)\n1\nelse\n2\n}")
#> {
#>   if (TRUE)
#>     1
#>     else
#>     2
#> }
```

Can we add braces around both the `if` and `else` parts here?

**Comment by lorenzwalthert** [comment]
Right... So I suggest to first fix the indention and later consider adding braces. If I recall correctly, the tidyverse style guide allows to drop curly braces if the statement fits on one line so I think ultimatively adding braces is the goal

**Comment by lorenzwalthert** [comment]
Depends on #128 in R/unindent.R.
