### ISSUE TITLE
Keep space between commas

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/styler#192]
``` r
styler::style_text("call(arg, , more_args)")
#> call(arg,, more_args)
styler::style_text("call(trailing, comma, )")
#> call(trailing, comma, )
```

The second example looks good, the first needs a space between the commas.

**Comment by lorenzwalthert** [comment]
Is this convention or a rule from the tidyverse style guide? I guess you cannot really derive it from section [2.2](http://style.tidyverse.org/syntax.html#spacing). 
> Always put a space after a comma, and never before (just like in regular English).

Also, the style guide clarifies in section [2.3](http://style.tidyverse.org/syntax.html#argument-names) that the following is bad style:

```r
# Bad
mean(x = 1:10, , FALSE)
```
So I wonder what we should do about that.

**Comment by krlmlr** [comment]
2.3 is about naming arguments vs. omitting arguments, but sometimes we do need to explicitly pass a missing argument, e.g. in `[`. In these rare cases I'd prefer the commas to be separated by space because this seems easier to read.

**Comment by krlmlr** [comment]
So maybe 2.2 needs an extension?

**Comment by lorenzwalthert** [comment]
Ok, I can file an issue.

**Comment by lorenzwalthert** [comment]
Well I just thought about it and maybe it's not worth an extension in the style guide since it is a very rare thing. I can just implement directly.
