### ISSUE TITLE
Multiline function definition without brace

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/styler#193]
``` r
styler::style_text("function()\nNULL")
#> function()
#> NULL
```

The `NULL` should be indented at least, maybe it should even receive braces or be moved one line up.

**Comment by lorenzwalthert** [comment]
I think moving one line up would be the simplest but maybe the function was intentionally put on a new line, e.g. if not everything does fit all on one line.

**Comment by lorenzwalthert** [comment]
Similar to #191 as far as adding braces goes.
