### ISSUE TITLE
add curly braces to if-else

### ISSUE THREAD

**Issue by lorenzwalthert** [krlmlr/styler#201]
If an if-else statement spans over mutliple lines, add curly braces, so 
``` r
#> {
#>   if (TRUE)
#>     1
#>   else
#>     2
#> }
```
Should be 
``` r
#> {
#>   if (TRUE) {
#>     1
#>   } else {
#>     2
#>   }
#> }
```

Follow-up of #191.

**Comment by lorenzwalthert** [comment]
@krlmlr Should that be a `strict = TRUE` transformation?

**Comment by krlmlr** [comment]
Currently we have both `strict = TRUE` and `scope = "token"`, which is a bit confusing. I think this definitely belongs in the "token" scope, not sure about strictness.

**Comment by lorenzwalthert** [comment]
Ok, let it be a `strict = TRUE` transformation since I think it can be legit to write:
```r
if (also_quite_long(call(a, lazy(other(call)))
  return(very_long(call(1+1, another, long, agrument)
```
