### ISSUE TITLE
Prevent R/RcppExports.R from getting formatted?

### ISSUE THREAD

**Issue by lorenzwalthert** [krlmlr/styler#215]
When reformatting `lubridate` with styler (https://github.com/tidyverse/lubridate/pull/577), with
```r
styler::style_pkg(...)
```

I found that R/RcppExports.R got overwritten when building the package and it uses single quotes plus slightly different formatting. I was wondering whether we should leave this file out for formatting.
I have no experience with Rcpp. Can you @krlmlr advise?

**Comment by krlmlr** [comment]
Generated files usually need to be left out.

**Comment by lorenzwalthert** [comment]
Ok. Any other files you can think of in this context?

**Comment by krlmlr** [comment]
No, but we may want to implement an opt-out, e.g., if the file contains a special comment.

**Comment by lorenzwalthert** [comment]
Or maybe `style_pkg()` should have an `exclude` option. I think lintr works with exclusion comments.

**Comment by krlmlr** [comment]
Looks reasonable to me, we could add the Rcpp comment as default then, or just always exclude.

**Comment by lorenzwalthert** [comment]
Do you refer to `#include <Rcpp.h> ` ? I thought Rcpp code always lives in non-.R files (which we don't style). Also, I think we should support either styling a whole file or not styling it at all - just for consistency. Ideally, we'd apply styler to all files (except for the ones that were generated automatically). I also did not know whether RcppExports.R is sensitive to single vs. double quotes.

**Comment by krlmlr** [comment]
`#include <Rcpp.h>` is a preprocessor directive for the C++ compiler, not a comment.

In RMariaDB, I see the following in the first two lines of `RcppExports.R`:

```r
# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
```

Better leave this file alone, because it will be overwritten anyway.

**Comment by lorenzwalthert** [comment]
Ok, so for now I will just exclude this file (hard-coded) and maybe we can open an issue to support a list of files to exclude at a later stage.

**Comment by krlmlr** [comment]
Sounds good.
