### ISSUE TITLE
installation error status 127

### ISSUE THREAD

**Issue by verajosemanuel** [krlmlr/styler#224]
> devtools::install_github("krlmlr/styler")
Downloading GitHub repo krlmlr/styler@master
from URL https://api.github.com/repos/krlmlr/styler/zipball/master
Installing styler
Downloading GitHub repo krlmlr/utf8@master
from URL https://api.github.com/repos/krlmlr/utf8/zipball/master
Error: running command '"C:/Users/joe/DOCUME~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 127

**Comment by lorenzwalthert** [comment]
Are you sure that `styler` causes the problem? Can you install `utf8` separately, preferably with `remotes`? 
`remotes::install_github("krlmlr/utf8")`

**Comment by lorenzwalthert** [comment]
If that works, you may want to try to use `remotes::install_github("krlmlr/styler")` instead of the corresponding `devtools` command, as `devtools` is being split up into smaller packages and active development may happen there (did not find any remarks about thaT in the `devtools` README  though).

**Comment by verajosemanuel** [comment]
* installing *source* package 'utf8' ...
** libs

*** arch - i386
Warning: comando ejecutado 'make -f "C:/Users/joe/DOCUME~1/R/R-34~1.1/etc/i386/Makeconf" -f "C:/Users/joe/DOCUME~1/R/R-34~1.1/share/make/winshlib.mk" SHLIB="utf8.dll" OBJECTS="encoding.o init.o"' tiene estatus 127
ERROR: compilation failed for package 'utf8'

**Comment by lorenzwalthert** [comment]
Maybe googling for the status 127 error helps. Latest version of Rtools etc. installed?

**Comment by verajosemanuel** [comment]
yes, RTools is installed. Searched error 127 to no avail. Tried reinstalling rtools latest version. No luck, but solved adding  C:\Rtools\MinGW\bin to PATH
