### ISSUE TITLE
if-else must be either on the same line or surrounded by braces

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/styler#229]
Currently:

``` r
styler::style_text("{\n if (TRUE) 1\nelse 2\n}")
#> {
#>   if (TRUE) {
#>     1
#>   } else 2
#> }
```

The braces around `1` are fine, need braces around `2` as well.

Reference: https://github.com/tidyverse/tibble/commit/1b532280647b6b4dfb7b4f59411b6a50b759c19f#commitcomment-24759540

**Comment by lorenzwalthert** [comment]
It was actually implemented with that use case in mind. The idea was to only add parenthesis if the 
expression after `if` or `else` was on a new line for `strict = TRUE`.
``` r
styler::style_text("{\n if (TRUE) 1\nelse \n2\n}")
#> {
#>   if (TRUE) {
#>     1
#>   } else {
#>     2
#>   }
#> }
```

With `strict = FALSE`, we do not add parenthesis.

``` r
styler::style_text("{\n if (TRUE) 1\nelse \n2\n}", strict = FALSE)
#> {
#>   if (TRUE) 1
#>   else
#>     2
#> }
```

**Comment by lorenzwalthert** [comment]
So how does the concrete desired implementation look like? Maybe we can produce the result from `strict = FALSE` with the current `strict = TRUE` solution and change `strict = TRUE` to what you @krlmlr suggest?

**Comment by krlmlr** [comment]
`strict = TRUE` should add braces also for the `else` part, `strict = FALSE` doesn't need to add any braces.
