### ISSUE TITLE
R version compatibility? Or other minimum versions?

### ISSUE THREAD

**Issue by jennybc** [krlmlr/styler#236]
Sorry this issue is a bit vague atm. In a branch, I've put styler into Suggests for reprex. reprex claims to work down to R 3.1 and I check this on travis. I know 3.1 is tricky right now due to purrr only recently becoming 3.1 compatible, so let's set that aside.

Here's the log file for reprex's failure on 3.2. The problem seems to be from styler. Does anything informative leap out at you?

https://travis-ci.org/tidyverse/reprex/jobs/286390103

**Comment by lorenzwalthert** [comment]
No, at least the error message does not seem to be related to be top-level styler source code (i.e. code we wrote in styler).

**Comment by lorenzwalthert** [comment]
I can't tell whether it is related to our only remote dependency (`krlmlr/utf8`) though. It seems as CI is run on current R versions [there](https://travis-ci.org/krlmlr/utf8/jobs/267075672).

**Comment by lorenzwalthert** [comment]
Well before CI was done with [tic](https://travis-ci.org/krlmlr/utf8/builds/267075671), it was also run on [R 3.3.3](https://travis-ci.org/krlmlr/utf8/jobs/267073016#L785) successfully I think, but apparently not on older versions.

**Comment by lorenzwalthert** [comment]
We could also ssh into travis for debugging as @krlmlr [did](https://twitter.com/krlmlr/status/889563067574611969).

**Comment by jennybc** [comment]
It would be interesting to know if your tests pass on 3.2.

**Comment by lorenzwalthert** [comment]
Yes, true. I just [set that up](https://travis-ci.org/lorenzwalthert/styler). The branch contains a few additional commits compared to master since I wanted to test with standard travis (instead of tic) anyways before the CRAN Submission. If they fail, I can remove those from the branch and we can see whether it still fails.

**Comment by lorenzwalthert** [comment]
Ok, the CI fails on R 3.2.5 early. Will look into it further.

**Comment by lorenzwalthert** [comment]
Reference: #237.

**Comment by lorenzwalthert** [comment]
@jennybc I think I spotted the problem after installing R 3.2 locally, running the tests and debugging. It was related to base R. See a34959ae. All tests pass with R 3.2.5 on [travis](https://travis-ci.org/lorenzwalthert/styler). Do you want to rebase on master and try again?

**Comment by jennybc** [comment]
Yes my 3.2 build is successful now 🎉 so that was it.

**Comment by lorenzwalthert** [comment]
Awesome.
