### ISSUE TITLE
Capitalise first letter in RStudio add-ins

### ISSUE THREAD

**Issue by hadley** [krlmlr/styler#239]
<img width="267" alt="screen shot 2017-10-12 at 11 16 19 am" src="https://user-images.githubusercontent.com/4196/31507015-d220050e-af3e-11e7-8bfc-fab88790b342.png">

**Comment by lorenzwalthert** [comment]
Thanks, will do adjust that.

**Comment by lorenzwalthert** [comment]
Thanks, will do that.
