### ISSUE TITLE
brace-parens and strict = FALSE

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/styler#248]
``` r
styler::style_text("list(\na = function() {\n  NULL}\n)")
#> list(
#>   a = function() {
#>     NULL
#>   }
#> )
styler::style_text("list(\na = function() {\n  NULL}\n)", strict = FALSE)
#> list(
#>   a = function() {
#>     NULL
#>   })
```

Why does `strict = FALSE` attach the paren to the closing brace? Quite invasive... ;-)

Use case: Styling testthat with `strict = FALSE` first (#240).

**Comment by lorenzwalthert** [comment]
We can add make `remove_line_break_before_round_closing()` inactive for `strict = FALSE`.
