### ISSUE TITLE
Use `dpylr::pull()` instead of `.[[1]]`

### ISSUE THREAD

**Issue by lorenzwalthert** [krlmlr/styler#25]
As introduced in the [release notes](https://github.com/tidyverse/dplyr/releases/tag/v0.7.0) of dplyr 0.7.0

**Comment by lorenzwalthert** [comment]
@krlmlr sorry but I can't actually see how that should work in our case. I think `pull` is intended to be used on data table, as the help file says, not on lists.

``` r
a <- list(c("(1+", "  2 + (", "    3 + 4", "  )", ")"))
a
#> [[1]]
#> [1] "(1+"       "  2 + ("   "    3 + 4" "  )"       ")"
a[[1]]
#> [1] "(1+"       "  2 + ("   "    3 + 4" "  )"       ")"
dplyr::pull(a)
#> Error in UseMethod("pull"): no applicable method for 'pull' applied to an object of class "list"
```

**Comment by krlmlr** [comment]
My mistake, I thought this construct was pulling out columns without actually reading it in full.
