### ISSUE TITLE
Function declarations

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/styler#253]
``` r
styler::style_text("function (a = 1,\nb = 2\n){\nNULL\n}", strict = FALSE, scope = "indention")
#> function (a = 1,
#>          b = 2
#>        ) {
#>   NULL
#> }
```

- [ ] The `b` argument needs to be aligned with the opening paren
- [ ] The closing paren and the opening brace should follow `b = 2`, or at least align with the opening paren

**Comment by lorenzwalthert** [comment]
Ok, I can do (1), so the reference for the indention level is `(` and not `function`. However, I then suggest to add a rule in `tidyverse_style` that removes spaces after `function` too.

**Comment by krlmlr** [comment]
With `strict = TRUE` the space after `function` is removed already.

**Comment by lorenzwalthert** [comment]
So do you think we should still remove it with `strict = FALSE` then?

**Comment by krlmlr** [comment]
It's fine either way as long as the next line aligns with the opening paren.

**Comment by lorenzwalthert** [comment]
Ok, I think the problem is that strict that it affects so many aspects of the styling that we might want to add other arguments for granular user control at some point.
