### ISSUE TITLE
creating a development branch

### ISSUE THREAD

**Issue by lorenzwalthert** [krlmlr/styler#33]
Since we are now about to make changes to the top-level functions and we have already a release out there, I suggest to submit all PRs against devel, so we can have a working branch.  @krlmlr what do you think?

**Comment by krlmlr** [comment]
master is our development branch, all releases are pushed to production: http://nvie.com/posts/a-successful-git-branching-model/. So the current situation seems fine to me.

**Comment by lorenzwalthert** [comment]
Ok. But how can production not be a branch? Is it just tags? What about installing our package from Github? Since the argument `ref` defaults to master in `remotes::install_github()`, will the installed version be the last commit in master or the one in production?

**Comment by krlmlr** [comment]
We do have a production branch in our repo, but `install_github()` installs from master on purpose. Could you please rephrase your question if necessary?

**Comment by lorenzwalthert** [comment]
Ok. Maybe I miss the obvious, but I can only see branches gh-pages and master in krlmlr/styler on GitHub, but no production branch. How come?

**Comment by krlmlr** [comment]
That's because I haven't pushed it yet until this very moment.
