### ISSUE TITLE
work with text instead of token

### ISSUE THREAD

**Issue by lorenzwalthert** [krlmlr/styler#36]
So far, all rules in R/rules.R operate on tokens, i.e. on this vector that contains tokens.
```r
op_token <- c(
  "'+'", "'-'", "'*'", "'/'", "'^'", "AND", "AND2", "EQ", "EQ_ASSIGN",
  "GE", "GT", "LE", "LEFT_ASSIGN", "LT", "NE", "OR", "OR2", "RIGHT_ASSIGN",
  "SPECIAL", "EQ_SUB", "ELSE")
```

For my PR #35, I was using the argument `op_token` in the function `indent_op()` in order to be consistent with previous work. It allows specifying all tokens that trigger indention. However, I think we should rather use text than token for two reasons:

* If people want to customise styler, they rather want to specify a text of a token (like `>=`) than spending time on figuring out what "LE", "GT" etc. stand for.
* More importantly, the token "SPECIAL" does not uniquely map to a text element, i.e. I suppose a case that is not covered by the tokens in `op_token` is declared as "SPECIAL". Hence, we can only define indention for all text elements corresponding to "SPECIAL".

How should we proceed?

**Comment by krlmlr** [comment]
Thanks. I think `"SPECIAL"` are user-defined operators. If there's a unique correspondence between text and token, we should be able to choose between either, but we need to handle `"SPECIAL"`, too. We could keep using the token and define a user-friendly mapping.

**Comment by lorenzwalthert** [comment]
#71 closes this issue since we work now with a modified text-token-mapping
