### ISSUE TITLE
releases are not "real" releases

### ISSUE THREAD

**Issue by lorenzwalthert** [krlmlr/styler#63]
It may have to to with tic, but I think our releases are not "real" releases, but rather just annotated tags with NEWS as the description, at least they don't look the same as releases from other repos (like [dplyr](https://github.com/tidyverse/dplyr/releases)). You can also not access any release information via `gh::gh("/repos/krlmlr/releases")` via the gh package for R.

**Comment by krlmlr** [comment]
I create annotated tags, this is just fine. Only CRAN releases get a corresponding GitHub release.

**Comment by lorenzwalthert** [comment]
Ok, did not know that. 👍
