### ISSUE TITLE
add a progress bar when top-level functions are called

### ISSUE THREAD

**Issue by lorenzwalthert** [krlmlr/styler#67]

**Comment by lorenzwalthert** [comment]
@krlmlr Since the workhorse function is `utf8::transform_lines_enc()`, maybe it would make sense to add dplyr-like progress bars there? At least when one transforms a whole bunch of files via `style_dir()`or `style_pkg()`, for `style_text()` I don't really see the use case of progress bars.

**Comment by krlmlr** [comment]
I don't think we need to change `transform_lines_enc()`: we can initialize and destroy any progress bar ourselves before calling this function, and then each transformer would add a step to the progress bar after completion.

**Comment by lorenzwalthert** [comment]
I think this can be declared closed with #163.
