### ISSUE TITLE
How to keep `=` as the assignment symbol?

### ISSUE THREAD

**Issue by ShixiangWang** [krlmlr/styler#860]
Dear developers,

Thanks for developing this awesome tool. Sometimes I want to use a style that keep using `=` instead of `<-` of assignment symbol. Is there any easy way to do this? I check the functions but no `options` can be used for this setting like `formatR`.

BTW, the package `languageserver` provide a way to do this in VScode with:

```R
options(languageserver.formatting_style = function(options) {
  style <- styler::tidyverse_style(indent_by = options$tabSize)
  style$token$force_assignment_op <- NULL # Not force modifying '=' to '<-'
  style
})
```

I don't know how to apply this for `styler` as no object can be assigned back.

Best,

Shixiang

**Comment by lorenzwalthert** [comment]
Related: #340.

**Comment by Robinlovelace** [comment]
Heads-up @lorenzwalthert and @ShixiangWang I have created a minimal {styler.equals} package building on Lorenz's great template: https://github.com/Robinlovelace/styler.equals 

Want to join forces on this @ShixiangWang? It's not yet CRAN ready as it has this message on checks, is this something that's worth fixing upstream, in the template @lorenzwalthert ? 

```
 All declared Imports should be used.
  Unexported objects imported by ':::' calls:
    ‘styler:::is_function_call’ ‘styler:::previous_non_comment’
    ‘styler:::scope_normalize’
    See the note in ?`:::` about the use of this operator.

0 errors ✔ | 0 warnings ✔ | 2 notes ✖
```
