### ISSUE TITLE
comments and line-breaks

### ISSUE THREAD

**Issue by lorenzwalthert** [krlmlr/styler#89]
Comments will currently not be moved to the end of a line if we change line breaks.
```r
a <- function(x) # 
{
  x + 1
}

```
becomes
```r
a <- function(x) # {
  x + 1
}
```

Which is really not what we want 😩. I think we talked about this case @krlmlr, but I just forgot about it.

**Comment by lorenzwalthert** [comment]
Any ideas how to solve that? Maybe we can use the pre_visitor to move the comment into the next child (top position) if there is no line break after the comment and then deal with it once we get to the child?

**Comment by krlmlr** [comment]
I'm fine with just leaving the code as is, i.e. don't strip newlines if the preceding token is a comment.
