### ISSUE TITLE
Indention of function declarations

### ISSUE THREAD

**Issue by krlmlr** [krlmlr/styler#94]
Example:

```r
a <- function(x, y,
              z)
{
}
```

To achieve this, we could:

1. When processing `z`, memoize the ID of `x` as a reference for the indent depth (because we can't know how deep `x` will be indented)
2. After applying all transformers, convert relative indents to absolute indents with a "pre" visitor
3. Flatten the nested structure with a "post" visitor
4. In the flat structure, update the absolute indention depth of `z` with that of `x` with a lookup in the flat structure
5. Serialize

We could omit step 3 if the reference token is always at the same level in the nested structure.

**Comment by lorenzwalthert** [comment]
Closed in favour of the more general #66
