### ISSUE TITLE
EOL spaces not dropped anymore

### ISSUE THREAD

**Issue by lorenzwalthert** [krlmlr/styler#98]
Since we removed `gsub()` [calls](8919160a6bed5c3d1b377d29537df93c8f766f0d), as discussed in #85, EOL spaces were not removed anymore.

``` r
library(styler)
nchar(style_text("#' "))
#> [1] 3
```

**Comment by krlmlr** [comment]
Only for comments, or also for regular code?

**Comment by lorenzwalthert** [comment]
Also for regular code, but it is solved with #99.
